%
% Collect Lapdog LBL constants. Must instantiate before using. Immutable.
%
%
% IMPLEMENTATION NOTE
% ===================
% Reasons for using a singleton class (instead of static methods & fields):
% 1) Can use properties/instance variables for "caching" values. Do not want to use persistent variables since they
% cause trouble when testing. NOTE: There are no proper static variables in MATLAB.
% 2) Can split up (structure, organize) configuration and validation code in methods.
% 3) The constructor can be used as initialization code which must be run before using the class/constants.
%
%
% DESIGN INTENT
% =============
% Should not take values from anywhere (through execution). ==> Should not read "global" constants (variables declared as
% "global". Ex: SATURATION_CONSTANT, N_FINAL_PRESWEEP_SAMPLES
%
%
% Initially created 2018-08-22 by Erik P G Johansson, IRF Uppsala
%
classdef constants < handle
    % PROPOSAL: Merge COTLF_HEADER_OPTIONS and ODL_INDENTATION_LENGTH (modify write_OBJTABLE_LBL_FILE accordingly).
    %   CON: Indentation length is more fundamental. Could pop up somewhere else.
    %   PROPOSAL: Modify write_OBJTABLE_LBL_FILE to merge header options into settings and copy the indentation length from
    %           the separate constant ODL_INDENTATION_LENGTH.
    %
    % NOTE: Used by non-Lapdog code: ./+EJ_lapdog_shared/+ro/+delivery/+geom/create_geom_TAB_LBL_from_EOG.m
    %       Might be used by future standalone, "Lapdogish" code (same git repo) for e.g. separately regenerating LBL files.
    %
    % PROPOSAL: Separately hard-code constant values just as Lapdog code does (duplication).
    %   PROPOSAL: Somehow check that constants set by Lapdog (lapdog, edder_lapdog, main) use the same constant values as "constants".
    %       PROPOSAL: (1) Internal hard-coded default values (MISSING_CONSTANT, and analogous if any). Constructor which accepts the
    %                 same variables/constants as arguments and checks them (assertion) against the internal (hard-coded) values. 
    %                 (2) Constructor call that just uses internally defined values.
    % 
    %       PROPOSAL: (1) Internal hard-coded default values 
    %                 (2) Constructor that looks for and compares with the corresponding global variables, if defined.
    %
    % NOTE: Not all constants here are really related to LBL files.
    %   Ex: MISSING_CONSTANT
    %       CON: Needed for LBL DESCRIPTION.
    %   Ex: N_FINAL_PRESWEEP_SAMPLES
    %       CON: Needed for LBL DESCRIPTION.
    %
    % PROPOSAL: Include metakernel_rosetta.txt
    %   PRO:/NOTE: Used by lapdog_convention_wrapper, get_lapdog_metakernel.
    
    properties(Access=public)
        ROSETTA_NAIF_ID                        = -226;     % Used by SPICE.
        ODL_INDENTATION_LENGTH                 = 4;
        MISSING_CONSTANT                       = -1000;    % Same as SATURATION_CONSTANT. Defined here so that it can be used by code that is not run/initialized via Lapdog.
        N_FINAL_PRESWEEP_SAMPLES               = 16;       % Number of pre-sweep samples to have. Unused samples positions are set to MISSING_CONSTANT.
        PRE_CREATELBL_SAVED_WORKSPACE_FILENAME = 'pre_createLBL_workspace.mat';
        PRE_CREATELBL_SAVED_INDEX_PREFIX       = 'pre_createLBL_workspace.index.';
        
        % When splitting "index" into multiple parts for saving to disk, this is how large every part should be, in
        % number of index values. Lapdog's ESC2 "index" variable is size "1x661300" and can be saved to disk as one
        % (empirically).
        % NOTE: The true upper limit may depend on the length of strings, in particular paths stored in "index". Should
        % maybe therefore lower the value to have more margin.
        N_INDEX_INDICES_PER_PART               = 662000;       
        %N_INDEX_INDICES_PER_PART               = 670;
        
        % Used by createLBL.create_OBJTABLE_LBL_file
        COTLF_HEADER_OPTIONS   % Set in constructor
        
        % Used for PDS keywords which are added to/included in LBL files, but whose values are not set by Lapdog. In
        % practise, these should be overwritten by Erik P G Johansson's "delivery code" (not included in Lapdog) before
        % actual delivery.
        % NOTE: Not inherently quoted. Usage may require adding quotes.
        VALUE_NOT_SET_BY_LAPDOG                = '<UNSET>';   
    end



    methods(Access=public)

        % Constructor
        % 
        function obj = constants(varargin)

            % ASSERTION: Find calls with non-zero number of arguments (old format).
            if nargin ~= 0
                error('Wrong number of arguments.')
            end
            
            % ASSERTION: Compare with global constant with the same meaning.
            if ismember('SATURATION_CONSTANT', who('global'))
                % CASE: SATURATION_CONSTANT is already a global constant, although it might not have been declared as
                % such in the current workspace.
                global SATURATION_CONSTANT
                if obj.MISSING_CONSTANT ~= SATURATION_CONSTANT
                    error('Global variable SATURATION_CONSTANT inconsistent with internally hard-coded MISSING_CONSTANT.')
                end                                
            end


            %==================================================================
            % LBL Header keys which should preferably come in a certain order.
            % Not all of them are required to be present.
            %==================================================================
            % Keywords which are quite independent of type of file.
            GENERAL_KEY_ORDER_LIST = { ...
                'PDS_VERSION_ID', ...    % The PDS standard requires this to be first, I think.
                ...
                'RECORD_TYPE', ...
                'RECORD_BYTES', ...
                'FILE_RECORDS', ...
                'FILE_NAME', ...
                '^TABLE', ...
                'DATA_SET_ID', ...
                'DATA_SET_NAME', ...
                'DATA_QUALITY_ID', ...
                'MISSION_ID', ...
                'MISSION_NAME', ...
                'MISSION_PHASE_NAME', ...
                'PRODUCER_INSTITUTION_NAME', ...
                'PRODUCER_ID', ...
                'PRODUCER_FULL_NAME', ...
                'LABEL_REVISION_NOTE', ...
                'PRODUCT_ID', ...
                'PRODUCT_TYPE', ...
                'PRODUCT_CREATION_TIME', ...
                'INSTRUMENT_HOST_ID', ...
                'INSTRUMENT_HOST_NAME', ...
                'INSTRUMENT_NAME', ...
                'INSTRUMENT_ID', ...
                'INSTRUMENT_TYPE', ...
                'INSTRUMENT_MODE_ID', ...
                'INSTRUMENT_MODE_DESC', ...
                'TARGET_NAME', ...
                'TARGET_TYPE', ...
                'PROCESSING_LEVEL_ID', ...
                'START_TIME', ...
                'STOP_TIME', ...
                'SPACECRAFT_CLOCK_START_COUNT', ...
                'SPACECRAFT_CLOCK_STOP_COUNT', ...
                'DESCRIPTION'};
            % Keywords which refer to very specific settings.
            RPCLAP_KEY_ORDER_LIST = { ...
                'ROSETTA:LAP_TM_RATE', ...
                'ROSETTA:LAP_BOOTSTRAP', ...
                ...
                'ROSETTA:LAP_FEEDBACK_P1', ...
                'ROSETTA:LAP_P1_ADC20', ...
                'ROSETTA:LAP_P1_ADC16', ...
                'ROSETTA:LAP_P1_RANGE_DENS_BIAS', ...
                'ROSETTA:LAP_P1_STRATEGY_OR_RANGE', ...
                'ROSETTA:LAP_P1_RX_OR_TX', ...
                'ROSETTA:LAP_P1_ADC16_FILTER', ...
                'ROSETTA:LAP_IBIAS1', ...
                'ROSETTA:LAP_VBIAS1', ...
                'ROSETTA:LAP_P1_BIAS_MODE', ...
                'ROSETTA:LAP_P1_INITIAL_SWEEP_SMPLS', ...
                'ROSETTA:LAP_P1_SWEEP_PLATEAU_DURATION', ...
                'ROSETTA:LAP_P1_SWEEP_STEPS', ...
                'ROSETTA:LAP_P1_SWEEP_START_BIAS', ...
                'ROSETTA:LAP_P1_SWEEP_FORMAT', ...
                'ROSETTA:LAP_P1_SWEEP_RESOLUTION', ...
                'ROSETTA:LAP_P1_SWEEP_STEP_HEIGHT', ...
                'ROSETTA:LAP_P1_ADC16_DOWNSAMPLE', ...
                'ROSETTA:LAP_P1_EFIELD_FIX_DURATION', ...
                'ROSETTA:LAP_SWEEPING_P1', ...
                'ROSETTA:LAP_P1_DENSITY_FIX_DURATION', ...
                ...
                'ROSETTA:LAP_FEEDBACK_P2', ...
                'ROSETTA:LAP_P2_ADC20', ...
                'ROSETTA:LAP_P2_ADC16', ...
                'ROSETTA:LAP_P2_RANGE_DENS_BIAS', ...
                'ROSETTA:LAP_P2_STRATEGY_OR_RANGE', ...
                'ROSETTA:LAP_P2_RX_OR_TX', ...
                'ROSETTA:LAP_P2_ADC16_FILTER', ...
                'ROSETTA:LAP_IBIAS2', ...
                'ROSETTA:LAP_VBIAS2', ...
                'ROSETTA:LAP_P2_BIAS_MODE', ...
                'ROSETTA:LAP_P2_INITIAL_SWEEP_SMPLS', ...
                'ROSETTA:LAP_P2_SWEEP_PLATEAU_DURATION', ...
                'ROSETTA:LAP_P2_SWEEP_STEPS', ...
                'ROSETTA:LAP_P2_SWEEP_START_BIAS', ...
                'ROSETTA:LAP_P2_SWEEP_FORMAT', ...
                'ROSETTA:LAP_P2_SWEEP_RESOLUTION', ...
                'ROSETTA:LAP_P2_SWEEP_STEP_HEIGHT', ...
                'ROSETTA:LAP_P2_ADC16_DOWNSAMPLE', ...
                'ROSETTA:LAP_P2_EFIELD_FIX_DURATION', ...
                'ROSETTA:LAP_SWEEPING_P2', ...
                'ROSETTA:LAP_P2_DENSITY_FIX_DURATION', ...
                ...
                'ROSETTA:LAP_P1P2_ADC20_STATUS', ...
                'ROSETTA:LAP_P1P2_ADC20_MA_LENGTH', ...
                'ROSETTA:LAP_P1P2_ADC20_DOWNSAMPLE'
                };
            KEY_ORDER_LIST = [GENERAL_KEY_ORDER_LIST, RPCLAP_KEY_ORDER_LIST];
            
            % Give error if encountering any of these keys.
            % Useful for obsoleted keys that should not exist anymore.
            FORBIDDEN_KEYS = { ...
                'ROSETTA:LAP_INITIAL_SWEEP_SMPLS', ...
                'ROSETTA:LAP_SWEEP_PLATEAU_DURATION', ...
                'ROSETTA:LAP_SWEEP_STEPS', ...
                'ROSETTA:LAP_SWEEP_START_BIAS', ...
                'ROSETTA:LAP_SWEEP_FORMAT', ...
                'ROSETTA:LAP_SWEEP_RESOLUTION', ...
                'ROSETTA:LAP_SWEEP_STEP_HEIGHT'};
            
            %         ADD_QUOTES_KEYS = { ...
            %             'DESCRIPTION', ...
            %             'SPACECRAFT_CLOCK_START_COUNT', ...
            %             'SPACECRAFT_CLOCK_STOP_COUNT', ...
            %             'INSTRUMENT_MODE_DESC', ...
            %             'ROSETTA:LAP_TM_RATE', ...
            %             'ROSETTA:LAP_BOOTSTRAP', ...
            %             'ROSETTA:LAP_FEEDBACK_P1', ...
            %             'ROSETTA:LAP_FEEDBACK_P2', ...
            %             'ROSETTA:LAP_P1_ADC20', ...
            %             'ROSETTA:LAP_P1_ADC16', ...
            %             'ROSETTA:LAP_P1_RANGE_DENS_BIAS', ...
            %             'ROSETTA:LAP_P1_STRATEGY_OR_RANGE', ...
            %             'ROSETTA:LAP_P1_RX_OR_TX', ...
            %             'ROSETTA:LAP_P1_ADC16_FILTER', ...
            %             'ROSETTA:LAP_P1_BIAS_MODE', ...
            %             'ROSETTA:LAP_P2_ADC20', ...
            %             'ROSETTA:LAP_P2_ADC16', ...
            %             'ROSETTA:LAP_P2_RANGE_DENS_BIAS', ...
            %             'ROSETTA:LAP_P2_STRATEGY_OR_RANGE', ...
            %             'ROSETTA:LAP_P2_RX_OR_TX', ...
            %             'ROSETTA:LAP_P2_ADC16_FILTER', ...
            %             'ROSETTA:LAP_P2_BIAS_MODE', ...
            %             'ROSETTA:LAP_P1P2_ADC20_STATUS', ...
            %             'ROSETTA:LAP_P1P2_ADC20_MA_LENGTH', ...
            %             'ROSETTA:LAP_P1P2_ADC20_DOWNSAMPLE', ...
            %             'ROSETTA:LAP_VBIAS1', ...
            %             'ROSETTA:LAP_VBIAS2', ...
            %             ...
            %             'ROSETTA:LAP_P1_INITIAL_SWEEP_SMPLS', ...
            %             'ROSETTA:LAP_P1_SWEEP_PLATEAU_DURATION', ...
            %             'ROSETTA:LAP_P1_SWEEP_STEPS', ...
            %             'ROSETTA:LAP_P1_SWEEP_START_BIAS', ...
            %             'ROSETTA:LAP_P1_SWEEP_FORMAT', ...
            %             'ROSETTA:LAP_P1_SWEEP_RESOLUTION', ...
            %             'ROSETTA:LAP_P1_SWEEP_STEP_HEIGHT', ...
            %             'ROSETTA:LAP_P1_ADC16_DOWNSAMPLE', ...
            %             'ROSETTA:LAP_SWEEPING_P1', ...
            %             ...
            %             'ROSETTA:LAP_P2_FINE_SWEEP_OFFSET', ...
            %             'ROSETTA:LAP_P2_INITIAL_SWEEP_SMPLS', ...
            %             'ROSETTA:LAP_P2_SWEEP_PLATEAU_DURATION', ...
            %             'ROSETTA:LAP_P2_SWEEP_STEPS', ...
            %             'ROSETTA:LAP_P2_SWEEP_START_BIAS', ...
            %             'ROSETTA:LAP_P2_SWEEP_FORMAT', ...
            %             'ROSETTA:LAP_P2_SWEEP_RESOLUTION', ...
            %             'ROSETTA:LAP_P2_SWEEP_STEP_HEIGHT', ...
            %             'ROSETTA:LAP_P2_ADC16_DOWNSAMPLE', ...
            %             'ROSETTA:LAP_SWEEPING_P2', ...
            %             'ROSETTA:LAP_P2_FINE_SWEEP_OFFSET'};
            
            % Keys for which quotes are added to the value if the values does not already have quotes.
            FORCE_QUOTE_KEYS = {...
                'DESCRIPTION', ...
                'SPACECRAFT_CLOCK_START_COUNT', ...
                'SPACECRAFT_CLOCK_STOP_COUNT'};
            
            obj.COTLF_HEADER_OPTIONS = struct(...
                'keyOrderList',        {KEY_ORDER_LIST}, ...
                'forbiddenKeysList',   {FORBIDDEN_KEYS}, ...
                'forceQuotesKeysList', {FORCE_QUOTE_KEYS});
        end
        

        
        % Construct list of key-value pairs to use for all LBL files.
        % 
        % Keys must not collide with keys set for specific file types.
        % For file types that read EDITED1/CALIB1 LBL files, must overwrite old keys(!).
        %
        % NOTE: Only keys that already exist in the CALIB files that are read (otherwise intentional error)
        %       and which are thus overwritten.
        % NOTE: Might not be complete.
        % NOTE: Contains many hardcoded constants, but not only.
        % NOTE: Does not contain timestamps (START/STOP_TIME, SPACECRAFT_CLOCK_START/STOP_COUNT).
        %
        % NOTE: Will not correctly assign all values, since they are overwritten in delivery code anyway. Simplifies
        % this code, and reduces the number of arguments. This however increases the number of errors if validating
        % EDDER/DERIV1 (not EDITED2/CALIB2/DERIV2) LBL files with e.g. "pvv label".
        
        function LblHeaderAllKvpl = get_LblHeaderAllKvpl(obj)
            % PROPOSAL: Use generate_PDS_data?
            % PROPOSAL: Change name. Something with "keywords" and not LBL only, which may refer to entire file.
            %
            % TODO-NEED-INFO: Required to add something like NOTE = "Cheops Reference Frame" ?
            
            QUOTED_VALUE_NOT_SET_BY_LAPDOG = ['"', obj.VALUE_NOT_SET_BY_LAPDOG, '"'];

            % IMPLEMENTATION NOTE: Including un-set LABEL_REVISION_NOTE meant to always be overwritten by other code. If
            % it is not overwritten, then create_OBJTABLE_LBL_file will give error.
            LblHeaderAllKvpl = EJ_lapdog_shared.utils.KVPL2({
                'PDS_VERSION_ID',            'PDS3'; ...
                'DATA_QUALITY_ID',           QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'PRODUCT_CREATION_TIME',     datestr(now, 'yyyy-mm-ddTHH:MM:SS.FFF'); ...
                'PRODUCT_TYPE',              QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'PROCESSING_LEVEL_ID',       QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                ...
                'DATA_SET_ID',               QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'DATA_SET_NAME',             QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'LABEL_REVISION_NOTE',       []; ...
                'PRODUCER_FULL_NAME',        QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'PRODUCER_ID',               obj.VALUE_NOT_SET_BY_LAPDOG; ...
                'PRODUCER_INSTITUTION_NAME', '"SWEDISH INSTITUTE OF SPACE PHYSICS, UPPSALA"'; ...
                'INSTRUMENT_HOST_ID',        'RO'; ...
                'INSTRUMENT_HOST_NAME',      '"ROSETTA-ORBITER"'; ...
                'INSTRUMENT_NAME',           '"ROSETTA PLASMA CONSORTIUM - LANGMUIR PROBE"'; ...
                'INSTRUMENT_TYPE',           '"PLASMA INSTRUMENT"'; ...
                'INSTRUMENT_ID',             'RPCLAP'; ...
                'TARGET_NAME',               QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'TARGET_TYPE',               QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...
                'MISSION_ID',                'ROSETTA'; ...
                'MISSION_NAME',              '"INTERNATIONAL ROSETTA MISSION"'; ...
                'MISSION_PHASE_NAME',        QUOTED_VALUE_NOT_SET_BY_LAPDOG; ...                
                }    ...
            );
        end
    end    % methods
end    % classdef
