%
% Create structure versions of tabindex and an_tabindex (cell arrays; prefix s=struct) for easier-to-use data structures.
%
%
% ARGUMENTS
% =========
% tabindex     : Cell array defined by other Lapdog code. Empty matrix is interpreted as 0x9
%                so that the caller can easily tell the function to generate an empty but properly formatted return
%                struct if the corresponding Lapdog variable is
%                   (1) undefined, or
%                   (2) defined but empty and not properly formatted.
%
%
% RETURN VALUES
% =============
% stabindex : Struct versions of tabindex. Every field is a cell array corresponding to one
%             column in tabindex.
%
%
%
% NOTE: The conversion must work for cell arrays with zero rows (cell(9,0)) and cell arrays with one item (cell(9,1)).
% NOTE: Old createLBL.m code contained a check for whether the tabindex{i,9} (iIndexLast) was empty (the cell array
% component, not the whole cell array). Why?
% Could not find any occurences of error message in any of the lap_agility logs (covering time interval 2014-06-13 -- 2016-06-16). /2016-06-16
% NOTE: Old code contained precautions for the cases that tabindex was empty. Why? Remove? Assertion?
function stabindex = convert_tabindex(tabindex)
    % PROPOSAL: Assertions on content of tabindex (every record).
    % PROPOSAL: Remove fields that are not used.

    % (Not assertion)
    if isempty(tabindex)
        %warning('tabindex is an EMPTY variable (0x0 array). - Modifying.');
        tabindex = cell(0, 9);
    end

    % ASSERTION
    if size(tabindex, 2) ~= 9
        if size(tabindex, 2) < 9
            error('Using old version of "tabindex" (presumably loaded from old cache, or generated by EDDER code)\n which this code version can not handle.')
        else
            error('tabindex has illegal number of columns.')
        end
    end

    stabindex = struct(...
        'path',            tabindex(:,1), ...   % Full path to file, including filename.
        'filename',        tabindex(:,2), ...   % Filename, without parent directory.
        'iIndexFirst',     tabindex(:,3), ...   % Index into "index". Change name?
        'iIndexLast',      tabindex(:,9), ...   % Index into "index". Change name?
        'utcStop',         tabindex(:,4), ...
        'sctStop',         tabindex(:,5), ...
        'nColumns',        tabindex(:,7) ...    % Used for sweep tables (IxS; varying number of columns).
        );
        %'nTabFileRows',    tabindex(:,6), ...   % Not used anymore (in createLBL).
        %'nTabBytesPerRow', tabindex(:,8) ...    % Not used anymore (in createLBL).

end
