%
% Create structure versions of tabindex and an_tabindex (cell arrays; prefix s=struct) for easier-to-use data structures.
%
%
% ARGUMENTS
% =========
% tabindex     : Cell array defined by other Lapdog code. Empty (0x0) is interpreted as 0x9.
%
%
% RETURN VALUES
% =============
% stabindex : Struct versions of tabindex. Every field is a cell array corresponding to one
%             column in tabindex.
%
%
%
% NOTE: The conversion must work for cell arrays with zero rows (cell(9,0)) and cell arrays with one item (cell(9,1)).
% NOTE: Old createLBL.m code contained a check for whether the tabindex{i,9} (i_index_last) was empty (the cell array
% component, not the whole cell array). Why?
% Could not find any occurences of error message in any of the lap_agility logs (covering time interval 2014-06-13 -- 2016-06-16). /2016-06-16
% NOTE: Old code contained precautions for the cases that tabindex was empty. Why? Remove? Assertion?
function stabindex = convert_tabindex(tabindex)

    % (Not assertion)
    if isempty(tabindex)
        warning('tabindex is an EMPTY variable (0x0 array). - Modifying.');
        tabindex = cell(0, 9);
    end

    % ASSERTION
    if size(tabindex, 2) ~= 9
        if size(tabindex, 2) < 9
            error('Using old version of "tabindex" (presumably loaded from old cache, or generated by EDDER code)\n which this code version can not handle.')
        else
            error('tabindex has illegal number of columns.')
        end
    end

    stabindex = struct(...
        'path',                tabindex(:,1), ...   % Full path to file, including filename.
        'filename',            tabindex(:,2), ...   % Filename, without parent directory.
        'i_index_first',       tabindex(:,3), ...   % Index into "index". Change name?
        'i_index_last',        tabindex(:,9), ...   % Index into "index". Change name?
        'UTC_stop',            tabindex(:,4), ...
        'SCT_stop',            tabindex(:,5), ...
        'N_TAB_file_rows',     tabindex(:,6), ...
        'N_columns',           tabindex(:,7), ...
        'N_TAB_bytes_per_row', tabindex(:,8) ...
        );

end
